CREATE TABLE IF NOT EXISTS registered_users (
  id BIGSERIAL PRIMARY KEY,

  email VARCHAR(254) NOT NULL UNIQUE,

  password_hash TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
